name: benchmark-env
channels:
- conda-forge
- defaults
dependencies:
- python==3.8
- pip
- numpy
- cython
- pip:
  - bigtree
  - biopython
  - dendropy
  - iow
  - seaborn
  - treeswift
  - https://github.com/etetoolkit/ete/archive/ete4.zip
